# Generated by Django 4.2.2 on 2023-07-01 11:33

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default='', upload_to=job.models.upload_image),
            preserve_default=False,
        ),
    ]
