# Generated by Django 4.2.2 on 2023-07-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to='photo/%y/%m/%d'),
        ),
    ]
